DO $$
DECLARE
  -- Put your CSV list here (quoted names, comma-separated)
  csv_names text := '"3 Quarter Sit-up",
"45° Side Bend",
"Air Bike",
"Alternate Heel Touchers",
"Alternate Lateral Pulldown",
"Assisted Chest Dip (Kneeling)",
"Assisted Parallel Close Grip Pull-up",
"Assisted Pull-up",
"Band Alternating Biceps Curl",
"Band Assisted Pull-up",
"Band Bent-over Hip Extension",
"Band One Arm Overhead Biceps Curl",
"Band One Arm Standing Low Row",
"Band One Arm Twisting Seated Row",
"Band Pull Through",
"Band Reverse Fly",
"Band Shoulder Press",
"Band Side Triceps Extension",
"Band Standing Rear Delt Row",
"Band Underhand Pulldown",
"Barbell Bench Front Squat",
"Barbell Bench Press",
"Barbell Bent Arm Pullover",
"Barbell Bent Over Row",
"Barbell Close-grip Bench Press",
"Barbell Curl",
"Barbell Deadlift",
"Barbell Decline Bench Press",
"Barbell Decline Bent Arm Pullover",
"Barbell Decline Wide-grip Press",
"Barbell Drag Curl",
"Barbell Floor Calf Raise",
"Barbell Front Raise",
"Barbell Front Squat",
"Barbell Full Squat",
"Barbell Full Zercher Squat",
"Barbell Good Morning",
"Barbell Hack Squat",
"Barbell Incline Bench Press",
"Barbell Incline Close Grip Bench Press",
"Barbell Incline Reverse-grip Press",
"Barbell Incline Row",
"Barbell Jm Bench Press",
"Barbell Lunge",
"Barbell Lying Back Of The Head Tricep Extension",
"Barbell Lying Close-grip Press",
"Barbell Lying Lifting (On Hip)",
"Barbell Lying Triceps Extension",
"Barbell Narrow Stance Squat",
"Barbell One Arm Bent Over Row",
"Barbell One Leg Squat",
"Barbell Palms Down Wrist Curl Over A Bench",
"Barbell Palms Up Wrist Curl Over A Bench",
"Barbell Pendlay Row",
"Barbell Preacher Curl",
"Barbell Press Sit-up",
"Barbell Rear Lunge",
"Barbell Reverse Wrist Curl V. 2",
"Barbell Reverse Curl",
"Barbell Reverse Grip Bent Over Row",
"Barbell Reverse Grip Incline Bench Row",
"Barbell Reverse Preacher Curl",
"Barbell Romanian Deadlift",
"Barbell Seated Behind Head Military Press",
"Barbell Seated Calf Raise",
"Barbell Seated Overhead Press",
"Barbell Shrug",
"Barbell Side Split Squat",
"Barbell Standing Close Grip Curl",
"Barbell Standing Close Grip Military Press",
"Barbell Standing Front Raise Over Head",
"Barbell Standing Overhead Triceps Extension",
"Barbell Standing Reverse Grip Curl",
"Barbell Standing Wide Grip Biceps Curl",
"Barbell Standing Wide-grip Curl",
"Barbell Straight Leg Deadlift",
"Barbell Sumo Deadlift",
"Barbell Upright Row",
"Barbell Wide Squat",
"Battling Ropes",
"Bench Dip (Knees Bent)",
"Bench Hip Extension",
"Bent Knee Lying Twist",
"Biceps Narrow Pull-ups",
"Bodyweight Drop Jump Squat",
"Bodyweight Standing Calf Raise",
"Bottoms-up",
"Cable Alternate Shoulder Press",
"Cable Alternate Triceps Extension",
"Cable Bar Lateral Pulldown",
"Cable Close Grip Curl",
"Cable Concentration Extension (On Knee)",
"Cable Cross-over Lateral Pulldown",
"Cable Cross-over Reverse Fly",
"Cable Cross-over Variation",
"Cable Curl",
"Cable Forward Raise",
"Cable Front Raise",
"Cable Front Shoulder Raise",
"Cable Hammer Curl (With Rope)",
"Cable High Pulley Overhead Tricep Extension",
"Cable High Row (Kneeling)",
"Cable Hip Adduction",
"Cable Incline Bench Press",
"Cable Incline Fly",
"Cable Judo Flip",
"Cable Kickback",
"Cable Kneeling Crunch",
"Cable Kneeling Rear Delt Row (With Rope)",
"Cable Lateral Pulldown (With Rope Attachment)",
"Cable Lateral Pulldown With V-bar",
"Cable Lateral Raise",
"Cable Low Fly",
"Cable Low Seated Row",
"Cable Middle Fly",
"Cable One Arm Bent Over Row",
"Cable One Arm Curl",
"Cable One Arm Lateral Raise",
"Cable One Arm Pulldown",
"Cable One Arm Straight Back High Row (Kneeling)",
"Cable One Arm Tricep Pushdown",
"Cable Overhead Curl",
"Cable Overhead Triceps Extension (Rope Attachment)",
"Cable Palm Rotational Row",
"Cable Pull Through (With Rope)",
"Cable Pulldown",
"Cable Pulldown (Pro Lat Bar)",
"Cable Pulldown Bicep Curl",
"Cable Pushdown",
"Cable Pushdown (With Rope Attachment)",
"Cable Rear Delt Row (Stirrups)",
"Cable Rear Drive",
"Cable Reverse Curl",
"Cable Reverse One Arm Curl",
"Cable Reverse-grip Pushdown",
"Cable Reverse-grip Straight Back Seated High Row",
"Cable Seated One Arm Alternate Row",
"Cable Seated Row",
"Cable Seated Wide-grip Row",
"Cable Side Crunch",
"Cable Standing Cross-over High Reverse Fly",
"Cable Standing Crunch",
"Cable Standing Crunch (With Rope Attachment)",
"Cable Standing Fly",
"Cable Standing Hip Extension",
"Cable Standing Rear Delt Row (With Rope)",
"Cable Standing Shoulder External Rotation",
"Cable Standing Up Straight Crossovers",
"Cable Straight Arm Pulldown",
"Cable Straight Arm Pulldown (With Rope)",
"Cable Thibaudeau Kayak Row",
"Cable Twist (Up-down)",
"Cable Upper Chest Crossovers",
"Cable Upper Row",
"Cable Wide Grip Rear Pulldown Behind Neck",
"Captains Chair Straight Leg Raise",
"Chest Dip",
"Chin-up",
"Close Grip Chin-up",
"Close-grip Push-up",
"Close-grip Push-up (On Knees)",
"Cross Body Crunch",
"Cycle Cross Trainer",
"Decline Crunch",
"Decline Push-up",
"Diamond Push-up",
"Dumbbell Alternate Biceps Curl",
"Dumbbell Alternate Hammer Preacher Curl",
"Dumbbell Alternate Seated Hammer Curl",
"Dumbbell Arnold Press",
"Dumbbell Arnold Press V. 2",
"Dumbbell Bench Press",
"Dumbbell Bench Seated Press",
"Dumbbell Bent Over Row",
"Dumbbell Biceps Curl",
"Dumbbell Close Grip Press",
"Dumbbell Concentration Curl",
"Dumbbell Deadlift",
"Dumbbell Fly",
"Dumbbell Front Raise",
"Dumbbell Hammer Curl",
"Dumbbell Incline Alternate Press",
"Dumbbell Incline Bench Press",
"Dumbbell Incline Biceps Curl",
"Dumbbell Incline Breeding",
"Dumbbell Incline Curl V. 2",
"Dumbbell Incline Fly",
"Dumbbell Incline Hammer Curl",
"Dumbbell Incline Hammer Press",
"Dumbbell Incline Row",
"Dumbbell Incline Triceps Extension",
"Dumbbell Kickback",
"Dumbbell Lateral Raise",
"Dumbbell Lateral To Front Raise",
"Dumbbell Lunge",
"Dumbbell Lying Triceps Extension",
"Dumbbell One Arm Bent-over Row",
"Dumbbell Over Bench Reverse Wrist Curl",
"Dumbbell Over Bench Wrist Curl",
"Dumbbell Palm Rotational Bent Over Row",
"Dumbbell Preacher Hammer Curl",
"Dumbbell Plyo Squat",
"Dumbbell Rear Delt Row (Shoulder)",
"Dumbbell Rear Fly",
"Dumbbell Rear Lateral Raise",
"Dumbbell Reverse Grip Biceps Curl",
"Dumbbell Reverse Grip Incline Bench Two Arm Row",
"Dumbbell Reverse Wrist Curl",
"Dumbbell Romanian Deadlift",
"Dumbbell Seated Bench Extension",
"Dumbbell Seated Bent Arm Lateral Raise",
"Dumbbell Seated Bicep Curl",
"Dumbbell Seated Biceps Curl To Shoulder Press",
"Dumbbell Seated Hammer Curl",
"Dumbbell Seated Inner Biceps Curl",
"Dumbbell Seated Lateral Raise",
"Dumbbell Seated Preacher Curl",
"Dumbbell Seated Reverse Grip Concentration Curl",
"Dumbbell Seated Shoulder Press",
"Dumbbell Seated Shoulder Press (Parallel Grip)",
"Dumbbell Seated Triceps Extension",
"Dumbbell Shrug",
"Dumbbell Side Plank With Rear Fly",
"Dumbbell Single Leg Split Squat",
"Dumbbell Standing Alternate Hammer Curl And Press",
"Dumbbell Standing Biceps Curl",
"Dumbbell Standing One Arm Extension",
"Dumbbell Standing Overhead Press",
"Dumbbell Standing Triceps Extension",
"Dumbbell Step-up",
"Dumbbell Upright Row",
"Dumbbell Waiter Biceps Curl",
"Dumbbell W-press",
"Dumbbell Zottman Curl",
"Dumbbell Zottman Preacher Curl",
"Ez Bar Lying Bent Arms Pullover",
"Ez Barbell Close Grip Preacher Curl",
"Ez Barbell Close-grip Curl",
"Ez Barbell Curl",
"Ez Barbell Incline Triceps Extension",
"Ez Barbell Reverse Grip Preacher Curl",
"Ez Barbell Seated Triceps Extension",
"Ez Barbell Spider Curl",
"Ez-bar Close-grip Bench Press",
"Forward Lunge",
"Front Plank With Twist",
"Hack Calf Raise",
"Hanging Leg Hip Raise",
"Hanging Leg Raise",
"Hip Raise (Bent Knee)",
"Incline Close-grip Push-up",
"Inverted Row",
"Kettlebell Swing",
"Leg Pull In Flat Bench",
"Lever Alternating Narrow Grip Seated Row",
"Lever Assisted Chin-up",
"Lever Back Extension",
"Lever Bent-over Row With V-bar",
"Lever Calf Press",
"Lever Chest Press",
"Lever Decline Chest Press",
"Lever Front Pulldown",
"Lever High Row",
"Lever Hip Extension V. 2",
"Lever Incline Chest Press",
"Lever Leg Extension",
"Lever Lying Leg Curl",
"Lever One Arm Bent Over Row",
"Lever One Arm Lateral Wide Pulldown",
"Lever One Arm Shoulder Press",
"Lever Preacher Curl",
"Lever Reverse Grip Lateral Pulldown",
"Lever Seated Fly",
"Lever Seated Hip Abduction",
"Lever Seated Hip Adduction",
"Lever Seated Leg Curl",
"Lever Seated Reverse Fly",
"Lever Seated Reverse Fly (Parallel Grip)",
"Lever Seated Squat Calf Raise On Leg Press Machine",
"Lever Standing Calf Raise",
"Mixed Grip Chin-up",
"Oblique Crunches Floor",
"Pull Up (Neutral Grip)",
"Pull-up",
"Push-up",
"Reverse Grip Pull-up",
"Run",
"Run (Equipment)",
"Russian Twist",
"Shoulder Grip Pull-up",
"Shoulder Tap",
"Shoulder Tap Push-up",
"Smith Bent Over Row",
"Smith Deadlift",
"Stationary Bike Run V. 3",
"Stationary Bike Walk",
"Twisted Leg Raise",
"Vertical Leg Raise (On Parallel Bars)",
"Walk Elliptical Cross Trainer",
"Walking On Incline Treadmill",
"Walking On Stepmill",
"Weighted Russian Twist (Legs Up)",
"Wheel Rollout",
"Wide Grip Pull-up"';

  provided_names text[];
  missing_name text;
  matched_name_count int := 0;
  updated_row_count int := 0;
BEGIN
  -- Parse CSV -> distinct cleaned names
  SELECT array_agg(name ORDER BY name)
  INTO provided_names
  FROM (
    SELECT DISTINCT nullif(trim(both '"' from trim(token)), '') AS name
    FROM regexp_split_to_table(csv_names, '\s*,\s*') AS token
  ) t
  WHERE name IS NOT NULL;

  IF provided_names IS NULL OR array_length(provided_names, 1) = 0 THEN
    RAISE EXCEPTION 'No exercise names parsed. Check csv_names format.';
  END IF;

  -- Reset all public library rows to false
  UPDATE exercises
  SET is_ai_routine_candidate = false
  WHERE user_id IS NULL;

  -- Set true only for provided names (case-insensitive)
  UPDATE exercises e
  SET is_ai_routine_candidate = true
  WHERE e.user_id IS NULL
    AND EXISTS (
      SELECT 1
      FROM unnest(provided_names) p(name)
      WHERE lower(p.name) = lower(e.name)
    );

  GET DIAGNOSTICS updated_row_count = ROW_COUNT;

  -- How many provided names matched at least one row
  SELECT count(*)
  INTO matched_name_count
  FROM unnest(provided_names) p(name)
  WHERE EXISTS (
    SELECT 1
    FROM exercises e
    WHERE e.user_id IS NULL
      AND lower(e.name) = lower(p.name)
  );

  RAISE NOTICE 'Done. Provided names: %, matched names: %, rows set true: %',
    array_length(provided_names, 1), matched_name_count, updated_row_count;

  -- Log each missing name
  FOR missing_name IN
    SELECT p.name
    FROM unnest(provided_names) p(name)
    WHERE NOT EXISTS (
      SELECT 1
      FROM exercises e
      WHERE e.user_id IS NULL
        AND lower(e.name) = lower(p.name)
    )
    ORDER BY p.name
  LOOP
    RAISE NOTICE 'NOT FOUND: %', missing_name;
  END LOOP;
END $$;
